# run command:  docker-compose up -d

version: '3.5'

name: lanchonete

services:
    app:
        container_name: lanchonete
        build:
            context: ./app
            dockerfile: Dockerfile
            args:
                MODE: dev # Docker compose é usado somente em ambiente Dev
        env_file:
            - .env
        ports:
            - 8080:8080
        depends_on:
            dbserver:
                condition: service_healthy
        networks:
            - app-network
            - external-network

    pagamento-mock:
        container_name: pagamento-mock
        build:
            context: ./pagamento-mock
            dockerfile: Dockerfile
            args:
                MODE: dev # Docker compose é usado somente em ambiente Dev
        env_file:
            - .env
        ports:
            - 8081:8080
        networks:
            - app-network
            - external-network

    messageQueue:
        container_name: messagequeue
        hostname: messagequeue
        image: rabbitmq:4.0.5-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        networks:
            - app-network

    dbserver:
        image: postgres:16.5-alpine3.20
        container_name: dbserver
        hostname: dbserver
        restart: always
        env_file:
            - ./.env
        environment:
            #           POSTGRES_MULTIPLE_DATABASES: "DB1","ownerOfDB1": "DB2","ownerOfDB2": ..."DB(n)", "ownerOfDB(n)"
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_HOST_AUTH_METHOD: md5
        healthcheck:
            test: ["CMD-SHELL", "psql -U ${DB_USER} -d ${DB_NAME} -c 'SELECT 1' || exit 1"]
            interval: 5s    # Time between health check attempts
            timeout: 5s     # Time to wait for a response from the health check command
            retries: 5      # Number of retries before marking the container as unhealthy
        ports:
            - 5433:5432
        networks:
            - app-network
        volumes:
            - ./volumes/data:/var/lib/postgresql/data
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 200M
                reservations:
                    cpus: '0.5'
                    memory: 200M

networks:
    app-network:
        name: app-net
        driver: bridge
        internal: true
        ipam:
            driver: default
            config:
                - subnet: 10.5.0.0/24

    external-network:
        name: lanch-net
        driver: bridge