apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mock-pagamento-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mock-pagamento-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 # Somente escalar se passar de 80%
