apiVersion: v1
kind: Service
metadata:
  name: mock-pagamento-service
spec:
  selector:
    app: mock-pagamento
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
