apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: lanchonete-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lanchonete-app
  template:
    metadata:
      labels:
        app: lanchonete-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret  # Kubernetes usará esta Secret para acessar a imagem privada
      containers:
        - name: lanchonete-app
          image: nicolassilvao/fiap-tech-challenge-lanchonete:latest  # Imagem privada no Docker Hub
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASS
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /api-docs
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api-docs
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10
      restartPolicy: Always