apiVersion: v1
kind: Service
metadata:
  name: messagequeue
spec:
  selector:
    app: messagequeue
  ports:
    - name: service
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: web
      protocol: TCP
      port: 15672
      targetPort: 15672
