apiVersion: v1
kind: PersistentVolumeClaim # Solicita armazenamento persistente no cluster. Mantém mesmo que o pod seja reiniciado ou recriado
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
