apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: guilhermefausto/tech_challenge_fiap_fase2_app:latest
          ports:
            - containerPort: 8080
#          envFrom:
#            - configMapRef:
#                name: app-config
#            - secretRef:
#                name: app-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"